language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
script:
  - npm test
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
